[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = '''
  set laststatus=2
  let g:lightline = {
    \ 'colorscheme': 'wombat'
    \ }
'''

[[plugins]]
repo = 'bronson/vim-trailing-whitespace'

[[plugins]]
repo = 'Yggdroot/indentLine'

[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add = '''
  let g:NERDTreeShowBookmarks=1
  let g:NERDTreeShowHidden=1
'''

[[plugins]]
repo = 'jistr/vim-nerdtree-tabs'
hook_add = '''
  let g:nerdtree_tabs_open_on_gui_startup=0
  nnoremap <Space>n :<C-u>NERDTreeTabsToggle<CR>
'''

[[plugins]]
repo = 'Shougo/neomru.vim'

[[plugins]]
repo = 'Shougo/unite.vim'
hook_add = '''
  nnoremap [unite] <Nop>
  nmap <Space>u [unite]

  nnoremap [unite]d :<C-u>Unite<Space>directory_mru<Space>-default-action=cd<CR>
  nnoremap [unite]b :<C-u>Unite<Space>buffer<CR>
  nnoremap [unite]m :<C-u>Unite<Space>file_mru<CR>
  nnoremap [unite]r :<C-u>Unite<Space>register<CR>
'''

[[plugins]]
repo = 'easymotion/vim-easymotion'
hook_add = '''
  " Move to line
  map <Space>L <Plug>(easymotion-bd-jk)
  nmap <Space>L <Plug>(easymotion-overwin-line)

  " Move to word
  map  <Space>w <Plug>(easymotion-bd-w)
  nmap <Space>w <Plug>(easymotion-overwin-w)

  let g:EasyMotion_do_mapping = 0
'''

[[plugins]]
repo = 'haya14busa/incsearch.vim'
hook_add = '''
  function! s:incsearch_config(...) abort
    return incsearch#util#deepextend(deepcopy({
    \   'modules': [incsearch#config#easymotion#module({'overwin': 1})],
    \   'keymap': {"\<C-l>": '<Over>(easymotion)'},
    \   'is_expr': 0
    \ }), get(a:, 1, {}))
  endfunction

  noremap <silent><expr> /  incsearch#go(<SID>incsearch_config())
  noremap <silent><expr> ?  incsearch#go(<SID>incsearch_config({'command': '?'}))
  noremap <silent><expr> g/ incsearch#go(<SID>incsearch_config({'is_stay': 1}))

  set hlsearch
  let g:incsearch#auto_nohlsearch = 1
  map n  <Plug>(incsearch-nohl-n)
  map N  <Plug>(incsearch-nohl-N)
  map *  <Plug>(incsearch-nohl-*)
  map #  <Plug>(incsearch-nohl-#)
  map g* <Plug>(incsearch-nohl-g*)
  map g# <Plug>(incsearch-nohl-g#)
'''

[[plugins]]
repo = 'haya14busa/incsearch-easymotion.vim'

[[plugins]]
repo = 'haya14busa/incsearch-migemo.vim'
hook_add = '''
  function! s:config_migemo(...) abort
    return extend(copy({
    \   'converters': [
    \     incsearch#config#migemo#converter(),
    \   ],
    \   'modules': [incsearch#config#easymotion#module({'overwin': 1})],
    \   'keymap': {"\<C-l>": '<Over>(easymotion)'},
    \   'is_expr': 0,
    \ }), get(a:, 1, {}))
  endfunction

  noremap <silent><expr> m/  incsearch#go(<SID>config_migemo())
  noremap <silent><expr> m?  incsearch#go(<SID>config_migemo({'command': '?'}))
  noremap <silent><expr> mg/ incsearch#go(<SID>config_migemo({'is_stay': 1}))
'''

# colorscheme
[[plugins]]
repo = 'altercation/vim-colors-solarized'
